server:
  port: 8001

mybatis:
  # mybatis配置文件所在路径
  config-location: classpath:mybatis.cfg.xml
  # 所有Entity别名类所在包
  type-aliases-package: com.mettre.provider.entity
  # mapper映射文件
  mapper-locations: classpath:mapper/**/*.xml



## Mybatis-plus
#mybatis-plus:
#  # 放在resource目录 classpath:/mapper/*Mapper.xml
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.mettre.wechat_information.pojo
#  typeEnumsPackage: com.mettre.wechat_information.pojo
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 2
#    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器MybatisPlusProperties
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    #逻辑删除配置（下面3个配置）
#    logic-delete-value: 0
#    logic-not-delete-value: 1
#    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
#    sql-parser-cache: true
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false




spring:
  application:
    # 对外暴露的微服务名字
    name: taobao-dept
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    # 数据库名称
    url: jdbc:mysql://localhost:3306/mettre_frame
    username: root
    password: admin
    dbcp2:
      # 数据库连接池的最小维持连接数
      min-idle: 5
      # 初始化连接数
      initial-size: 5
      # 最大连接数
      max-total: 5
      # 等待连接获取的最大超时时间
      max-wait-millis: 200